// Generated by gencpp from file arm_gazebo/ikRequest.msg
// DO NOT EDIT!


#ifndef ARM_GAZEBO_MESSAGE_IKREQUEST_H
#define ARM_GAZEBO_MESSAGE_IKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_gazebo
{
template <class ContainerAllocator>
struct ikRequest_
{
  typedef ikRequest_<ContainerAllocator> Type;

  ikRequest_()
    : joint_positions()
    , actuator_pose()  {
    }
  ikRequest_(const ContainerAllocator& _alloc)
    : joint_positions(_alloc)
    , actuator_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_positions_type;
  _joint_positions_type joint_positions;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _actuator_pose_type;
  _actuator_pose_type actuator_pose;





  typedef boost::shared_ptr< ::arm_gazebo::ikRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_gazebo::ikRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ikRequest_

typedef ::arm_gazebo::ikRequest_<std::allocator<void> > ikRequest;

typedef boost::shared_ptr< ::arm_gazebo::ikRequest > ikRequestPtr;
typedef boost::shared_ptr< ::arm_gazebo::ikRequest const> ikRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_gazebo::ikRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_gazebo::ikRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_gazebo::ikRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::ikRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_positions == rhs.joint_positions &&
    lhs.actuator_pose == rhs.actuator_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_gazebo::ikRequest_<ContainerAllocator1> & lhs, const ::arm_gazebo::ikRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::ikRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_gazebo::ikRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::ikRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_gazebo::ikRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::ikRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_gazebo::ikRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_gazebo::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db792127185cdcf354b6e7c7086f5a4a";
  }

  static const char* value(const ::arm_gazebo::ikRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb792127185cdcf3ULL;
  static const uint64_t static_value2 = 0x54b6e7c7086f5a4aULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_gazebo::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_gazebo/ikRequest";
  }

  static const char* value(const ::arm_gazebo::ikRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_gazebo::ikRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_positions\n"
"float64[] actuator_pose\n"
;
  }

  static const char* value(const ::arm_gazebo::ikRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_gazebo::ikRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_positions);
      stream.next(m.actuator_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ikRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_gazebo::ikRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_gazebo::ikRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
    s << indent << "actuator_pose[]" << std::endl;
    for (size_t i = 0; i < v.actuator_pose.size(); ++i)
    {
      s << indent << "  actuator_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.actuator_pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_GAZEBO_MESSAGE_IKREQUEST_H
