// Generated by gencpp from file question1/input.msg
// DO NOT EDIT!


#ifndef QUESTION1_MESSAGE_INPUT_H
#define QUESTION1_MESSAGE_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace question1
{
template <class ContainerAllocator>
struct input_
{
  typedef input_<ContainerAllocator> Type;

  input_()
    : posvectors()
    , posangles()
    , d(0.0)  {
      posvectors.assign(0.0);

      posangles.assign(0.0);
  }
  input_(const ContainerAllocator& _alloc)
    : posvectors()
    , posangles()
    , d(0.0)  {
  (void)_alloc;
      posvectors.assign(0.0);

      posangles.assign(0.0);
  }



   typedef boost::array<float, 3>  _posvectors_type;
  _posvectors_type posvectors;

   typedef boost::array<float, 3>  _posangles_type;
  _posangles_type posangles;

   typedef float _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::question1::input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::question1::input_<ContainerAllocator> const> ConstPtr;

}; // struct input_

typedef ::question1::input_<std::allocator<void> > input;

typedef boost::shared_ptr< ::question1::input > inputPtr;
typedef boost::shared_ptr< ::question1::input const> inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::question1::input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::question1::input_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::question1::input_<ContainerAllocator1> & lhs, const ::question1::input_<ContainerAllocator2> & rhs)
{
  return lhs.posvectors == rhs.posvectors &&
    lhs.posangles == rhs.posangles &&
    lhs.d == rhs.d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::question1::input_<ContainerAllocator1> & lhs, const ::question1::input_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace question1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::question1::input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::question1::input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::question1::input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::question1::input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::question1::input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::question1::input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::question1::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78254569331848474f925dd56629aa0d";
  }

  static const char* value(const ::question1::input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7825456933184847ULL;
  static const uint64_t static_value2 = 0x4f925dd56629aa0dULL;
};

template<class ContainerAllocator>
struct DataType< ::question1::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "question1/input";
  }

  static const char* value(const ::question1::input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::question1::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] posvectors \n"
"float32[3] posangles \n"
"float32 d\n"
;
  }

  static const char* value(const ::question1::input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::question1::input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posvectors);
      stream.next(m.posangles);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::question1::input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::question1::input_<ContainerAllocator>& v)
  {
    s << indent << "posvectors[]" << std::endl;
    for (size_t i = 0; i < v.posvectors.size(); ++i)
    {
      s << indent << "  posvectors[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.posvectors[i]);
    }
    s << indent << "posangles[]" << std::endl;
    for (size_t i = 0; i < v.posangles.size(); ++i)
    {
      s << indent << "  posangles[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.posangles[i]);
    }
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUESTION1_MESSAGE_INPUT_H
